project:
  type: website

website:
  title: "Ayu & Bas"
  search: false
  navbar:
    title: false
    right:
      - href: english.qmd
        text: ğŸ‡¬ğŸ‡§
      - href: bahasa.qmd
        text: ğŸ‡®ğŸ‡©

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

execute:
  freeze: auto
